##### ----GET All Books (sorted) ----
GET http://localhost:3000/db-api/all-books-sum?sort=FAVOURITE&order=DESC
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVU0VSX0lEIjoiMSIsIlJPTEUiOiJlbXBsb3llZSIsImlhdCI6MTY5Mjk2ODU3NCwiZXhwIjoxNjkzMDU0OTc0fQ.9SiASZrIMKpC6YGDPaDjKtRwzX5w5kLraJKIV7mLcE0

###OUTPUT
[
  {
    "ISBN": "9780747591269",
    "TITLE": "Harry Potter and the Order of the Phoenix",
    "IMAGE": "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/bc4625241f54_86391.jpg",
    "PUBLISH_YEAR": null,
    "PAGE": 901,
    "LANGUAGE": "English",
    "AUTHORS": "J. K. Rowling",
    "RATING": 0,
    "PUBLISHER": "Bloomsbury Publishing"
  },
  {
    "ISBN": "9780439785969",
    "TITLE": "Harry Potter and the Half-Blood Prince",
    "IMAGE": "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/127d59aff684_102401.gif",
    "PUBLISH_YEAR": 2005,
    "PAGE": 652,
    "LANGUAGE": "English",
    "AUTHORS": "J. K. Rowling",
    "RATING": 0,
    "PUBLISHER": "Bloomsbury Publishing"
  }
]

#### ----GET Single Book ----
GET http://localhost:3000/db-api/book?id=9781408855652

###OUTPUT

{
  "ISBN": "9781408855652",
  "TITLE": "Harry Potter and the Philosophers Stone",
  "IMAGE": "https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/4cf25a33d8a4_86392.gif",
  "NUMBER_OF_PAGES": 352,
  "LANGUAGE": "English",
  "PUBLISH_YEAR": 1997,
  "DESCRIPTION": "Harry Potter discovers he's a wizard on his eleventh birthday and is invited to attend Hogwarts School of Witchcraft and Wizardry. There, he makes friends, learns magic, and uncovers the mystery of the Sorcerer's Stone.",
  "PUBLISHER_ID": "1",
  "PUBLISHER_NAME": "Bloomsbury Publishing",
  "PUBLISHER_EMAIL": "contact@bloomsbury.com",
  "PUBLISHER_CONTACT_NO": "+44 (0)20 7631 5600",
  "PUBLISHER_ADDRESS": "WC1B 3DP, London, England",
  "PUBLISHER_IMAGE": "https://media-exp1.licdn.com/dms/image/C4E0BAQEDkPybVXr47Q/company-logo_200_200/0/1544531682586?e=2159024400&v=beta&t=JjAs9ok_PwgXA9CFsXKm3bt6fjbFI4N7SZRn4ajOUVg",
  "AUTHOR_NAME": "J. K. Rowling"
}

#### ----POST user ----
POST http://localhost:3000/db-api/user/signup
Content-Type: application/json

{
  "firstName": "jakaria",
  "lastName": "hossain",
  "image": "https://drive.google.com/file/d/1hKQvVs_HB15yfH6wj_Ca08iPeUSCEsw2/view?usp=sharing",
  "address": "pabna, bangladesh",
  "email": "abcd@gmail.com",
  "password": "1234",
  "contactNo": "01712345678",
  "gender": "M"
}

### OUTPUT
{
  "auth": true,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVU0VSX0lEIjoiMTAiLCJST0xFIjoidXNlciIsImlhdCI6MTY5Mjk1NTMxMSwiZXhwIjoxNjkzMDQxNzExfQ._LVML8OMQEVJBL-vVSWI3SilxOP16M-HT57gHRZrQEI",
  "role": "user"
}

#### ----LOGIN user ----
POST http://localhost:3000/db-api/general/login
Content-Type: application/json

{
  "EMAIL": "ryangeorge@gmail.com",
  "PASSWORD": "ryanMonster300"
}

# {
#   "EMAIL": "mdjakaria442020@gmail.com",
#   "PASSWORD": "Jakaria63"
# }

# {
#   "EMAIL": "a.n.swapnil2003@gmail.com",
#   "PASSWORD": "Ans2003"
# }

###OUTPUT
{
  "auth": true,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVU0VSX0lEIjoiMyIsIlJPTEUiOiJ1c2VyIiwiaWF0IjoxNjkyOTAyMjc3LCJleHAiOjE2OTI5ODg2Nzd9.2heH3mdS22r7NZSFud5viNBWjyP5WDF3iyrRLwSp3pw",
  "rule": "user"
}

#### ----POST admin ----
POST http://localhost:3000/db-api/admin/signup
Content-Type: application/json

{
  "FIRST_NAME": "Jakaria",
  "LAST_NAME": "Hossain",
  "IMAGE": "https://drive.google.com/file/d/1VzQYM8sLT1EtWOVk1w-pUGeQuIR-44DY/view?usp=sharing",
  "ADDRESS": "Pabna, Bangladesh",
  "EMAIL": "mdjakaria442020@gmail.com",
  "PASSWORD": "Jakaria63",
  "CONTACT_NO": "01790-715232",
  "GENDER": "M"
}

###OUTPUT
{
  "auth": true,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVU0VSX0lEIjoiNiIsIlJPTEUiOiJhZG1pbiIsImlhdCI6MTY5MjkwNTIyMSwiZXhwIjoxNjkyOTkxNjIxfQ.R3SLG83aPG1U7RYSRX5FNmpjZd_nRHP3J_onXxRkYyY",
  "rule": "admin"
}
