-- AUTHOR
INSERT INTO c##library.AUTHOR (AUTHOR_ID, NAME, IMAGE, BIO,DoB,DoD,NATIONALITY) VALUES (1, 'J. K. Rowling',  'https://ds.rokomari.store/rokomari110/people/6ed601ea2b54_2559.png', 'Joan Rowling, author of the popular Harry Potter series, K. Known as Rowling, she was born on July 31, 1985, in Yate, Gloucestershire, England. Ever since he was a child, he has been addicted to story books, and he loved to write new stories. Listening to her younger sister tell her own story, she started dreaming of becoming a great writer. He spent his childhood in a rural environment. After graduating from the University of Exeter, he began his career as an English teacher, but had to move to Portugal. Later when she came to Edinburgh from Portugal, she was the mother of one child, single mother. When he arrived in Edinburgh, he read financially. Originally he had to hold a pen in his hand in search of money, the result of which is the world famous fiction ''Harry Potter''. Joan Rowling became one of the most well-known literary figures in today''s literary world, as an orphaned simple boy discovered the existence of magic in himself and gradually wrote strange and unimaginable stories that happened in his life. K. Rowling ''. The commercially successful series brought back its fortunes and forced bookworms of all ages to wander into that world of magical fairy tales. J. K. Rowling''s books include a total of six books in the Harry Potter series. These 6 books have earned the title of bestseller worldwide and have sold more than 450 million copies so far. J. K. Rowling''s books include Harry Potter and the Philosopher''s Stone, Harry Potter and the Chamber of Secrets, Harry Potter and the Prisoner of Azkaban, Harry Potter and the Goblet of Fire, and Harry. ''The Order of the Phoenix'', ''Harry Potter and the Half-Blood Prince'', ''Harry Potter and the Deathly Hallows'','' The Casual Vacancy '','' Cuckoo''s Calling '','' The Silkworm '','' Career of Evil '','' Lethal White ''etc. He also co-wrote the play Harry Potter and the Cursed Child with Jack Thorne and John Tiffany. English language as well as J. K. Rowling''s translation books are equally popular. The author of this billionaire has also been contributing to the society through donations to various charities.', '31-07-1965','30-12-1990', 'British');

--PUBLISHER
INSERT INTO c##library.PUBLISHER (PUBLISHER_ID, NAME, IMAGE, CONTACT_NO, EMAIL, CITY, COUNTRY, POSTAL_CODE) VALUES (1, 'Bloomsbury Publishing','https://media-exp1.licdn.com/dms/image/C4E0BAQEDkPybVXr47Q/company-logo_200_200/0/1544531682586?e=2159024400&v=beta&t=JjAs9ok_PwgXA9CFsXKm3bt6fjbFI4N7SZRn4ajOUVg', '+44 (0)20 7631 5600', 'contact@bloomsbury.com','London', 'England', 'WC1B 3DP' );

--
INSERT INTO c##library.BOOK (PUBLISHER_ID, PUBLISH_YEAR,  LANGUAGE, IMAGE, TITLE, ISBN, NUMBER_OF_PAGES,  DESCRIPTION  ) VALUES ( 1, 1997,   'English', 'https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/4cf25a33d8a4_86392.gif', 'Harry Potter and the Philosophers Stone', '9781408855652', 352, 'Harry Potter discovers he''s a wizard on his eleventh birthday and is invited to attend Hogwarts School of Witchcraft and Wizardry. There, he makes friends, learns magic, and uncovers the mystery of the Sorcerer''s Stone.');
INSERT INTO c##library.BOOK (PUBLISHER_ID, PUBLISH_YEAR,  LANGUAGE, IMAGE, TITLE, ISBN, NUMBER_OF_PAGES,  DESCRIPTION  ) VALUES ( 1, 1998,   'English', 'https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/58c09b4d2824_110120.gif', 'Harry Potter and the Chamber of Secrets ', '9781408855669', 384, 'Harry returns to Hogwarts for his second year, only to find the school plagued by mysterious attacks. With the help of his friends, he investigates the legend of the Chamber of Secrets and its monstrous secrets.'  );
INSERT INTO c##library.BOOK (PUBLISHER_ID, PUBLISH_YEAR,  LANGUAGE, IMAGE, TITLE, ISBN, NUMBER_OF_PAGES,  DESCRIPTION  ) VALUES ( 1, 1999,  'English', 'https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/a5a669963_101016.jpg', 'Harry Potter and the Prisoner of Azkaban', '9781408855676', 462, 'In his third year, Harry learns that an escaped prisoner, Sirius Black, is believed to be after him. With new magical creatures and revelations about his past, Harry uncovers the truth behind Sirius''s escape.' );
INSERT INTO c##library.BOOK (PUBLISHER_ID, PUBLISH_YEAR,  LANGUAGE, IMAGE, TITLE, ISBN, NUMBER_OF_PAGES,  DESCRIPTION  ) VALUES ( 1, 2000,   'English', 'https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/629765c8f_152119.jpg', 'Harry Potter and the Goblet of Fire', '9781408834992', 640, 'Harry is unexpectedly entered into the dangerous Triwizard Tournament, competing against older students. But as the tournament progresses, dark forces are at work, leading to a shocking turn of events.'  );
INSERT INTO c##library.BOOK (PUBLISHER_ID, PUBLISH_YEAR,  LANGUAGE, IMAGE, TITLE, ISBN, NUMBER_OF_PAGES,  DESCRIPTION  ) VALUES ( 1, null,  'English', 'https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/bc4625241f54_86391.jpg', 'Harry Potter and the Order of the Phoenix', '9780747591269', 901, 'As Harry enters his fifth year, he faces resistance from the Ministry of Magic and his peers who doubt his claims about the return of Lord Voldemort. He forms "Dumbledore''s Army" to teach his friends defensive magic.' );
INSERT INTO c##library.BOOK (PUBLISHER_ID, PUBLISH_YEAR,  LANGUAGE, IMAGE, TITLE, ISBN, NUMBER_OF_PAGES,  DESCRIPTION  ) VALUES ( 1, 2005, 'English', 'https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/127d59aff684_102401.gif', 'Harry Potter and the Half-Blood Prince', '9780439785969', 652 'Voldemort''s power is growing, and Harry learns about his enemy''s past through memories collected in a mysterious book. Meanwhile, he navigates teenage emotions and the challenges of preparing for the final battle.' );
INSERT INTO c##library.BOOK (PUBLISHER_ID, PUBLISH_YEAR,  LANGUAGE, IMAGE, TITLE, ISBN, NUMBER_OF_PAGES,  DESCRIPTION  ) VALUES ( 1, null,  'English', 'https://ds.rokomari.store/rokomari110/ProductNew20190903/130X186/Harry_Potter_and_the_Deathly_Hallows_(Se-J.K_Rowling-699a7-122325.jpg', 'Harry Potter and the Deathly Hallows', '9781408894743', 608, 'In the final book, Harry, Ron, and Hermione go on a dangerous mission to destroy Horcruxes, Voldemort''s secret to immortality. The trio faces their most challenging obstacles and makes ultimate sacrifices.');

INSERT INTO c##library.WRITTEN_BY(ISBN,AUTHOR_ID) VALUES('9781408855652','1');
INSERT INTO c##library.WRITTEN_BY(ISBN,AUTHOR_ID) VALUES('9781408855669','1');
INSERT INTO c##library.WRITTEN_BY(ISBN,AUTHOR_ID) VALUES('9781408855676','1');
INSERT INTO c##library.WRITTEN_BY(ISBN,AUTHOR_ID) VALUES('9781408834992','1');
INSERT INTO c##library.WRITTEN_BY(ISBN,AUTHOR_ID) VALUES('9780747591269','1');
INSERT INTO c##library.WRITTEN_BY(ISBN,AUTHOR_ID) VALUES('9780439785969','1');
INSERT INTO c##library.WRITTEN_BY(ISBN,AUTHOR_ID) VALUES('9781408894743','1');
