/*
 Navicat Premium Data Transfer

 Source Server         : Library
 Source Server Type    : Oracle
 Source Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 Source Host           : localhost:1521
 Source Schema         : C##LIBRARY

 Target Server Type    : Oracle
 Target Server Version : 190000 (Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production)
 File Encoding         : 65001

 Date: 14/08/2023 15:28:21
*/


-- ----------------------------
-- Table structure for ADMIN
-- ----------------------------
DROP TABLE "C##LIBRARY"."ADMIN";
CREATE TABLE "C##LIBRARY"."ADMIN" (
    "USER_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for APPLY
-- ----------------------------
DROP TABLE "C##LIBRARY"."APPLY";
CREATE TABLE "C##LIBRARY"."APPLY" (
                                      "USER_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                      "JOB_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                      "APPLY_DATE" DATE VISIBLE NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for AUTHOR
-- ----------------------------
DROP TABLE "C##LIBRARY"."AUTHOR";
CREATE TABLE "C##LIBRARY"."AUTHOR" (
                                       "AUTHOR_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                       "DOB" DATE VISIBLE NOT NULL,
                                       "DOD" DATE VISIBLE,
                                       "NATIONALITY" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                       "IMAGE" VARCHAR2(200 BYTE) VISIBLE DEFAULT 'https://previews.123rf.com/images/anatolir/anatolir1712/anatolir171201476/91832679-man-avatar-icon-flat-illustration-of-man-avatar-vector-icon-isolated-on-white-background.jpg',
                                       "NAME" VARCHAR2(50 BYTE) VISIBLE NOT NULL,
                                       "BIO" VARCHAR2(3000 BYTE) VISIBLE
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for BOOK
-- ----------------------------
DROP TABLE "C##LIBRARY"."BOOK";
CREATE TABLE "C##LIBRARY"."BOOK" (
                                     "ISBN" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
                                     "TITLE" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
                                     "NUMBER_OF_PAGES" NUMBER VISIBLE NOT NULL,
                                     "LANGUAGE" VARCHAR2(10 BYTE) VISIBLE,
                                     "DESCRIPTION" VARCHAR2(2000 BYTE) VISIBLE,
                                     "PUBLISHER_ID" VARCHAR2(20 BYTE) VISIBLE,
                                     "IMAGE" VARCHAR2(200 BYTE) VISIBLE DEFAULT 'https://st2.depositphotos.com/5703046/12114/i/950/depositphotos_121142344-stock-photo-white-book-on-white-background.jpg',
                                     "PUBLISH_YEAR" NUMBER VISIBLE
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for BOOK_GENRE
-- ----------------------------
DROP TABLE "C##LIBRARY"."BOOK_GENRE";
CREATE TABLE "C##LIBRARY"."BOOK_GENRE" (
                                           "ISBN" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
                                           "GENRE_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for EDITION
-- ----------------------------
DROP TABLE "C##LIBRARY"."EDITION";
CREATE TABLE "C##LIBRARY"."EDITION" (
                                        "EDITION_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                        "ISBN" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
                                        "EDITION_NUM" NUMBER VISIBLE NOT NULL,
                                        "NUM_OF_COPIES" NUMBER VISIBLE NOT NULL,
                                        "PUBLISH_YEAR" NUMBER VISIBLE
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for EMPLOYEE
-- ----------------------------
DROP TABLE "C##LIBRARY"."EMPLOYEE";
CREATE TABLE "C##LIBRARY"."EMPLOYEE" (
                                         "USER_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                         "JOB_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                         "JOIN_DATE" DATE VISIBLE NOT NULL,
                                         "END_DATE" DATE VISIBLE
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FAVOURITE
-- ----------------------------
DROP TABLE "C##LIBRARY"."FAVOURITE";
CREATE TABLE "C##LIBRARY"."FAVOURITE" (
                                          "USER_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                          "ISBN" VARCHAR2(100 BYTE) VISIBLE NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FINE_HISTORY
-- ----------------------------
DROP TABLE "C##LIBRARY"."FINE_HISTORY";
CREATE TABLE "C##LIBRARY"."FINE_HISTORY" (
                                             "RENT_HISTORY_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                             "FEE_AMOUNT" NUMBER VISIBLE NOT NULL,
                                             "START_DATE" DATE VISIBLE NOT NULL,
                                             "PAYMENT_DATE" DATE VISIBLE
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for GENRE
-- ----------------------------
DROP TABLE "C##LIBRARY"."GENRE";
CREATE TABLE "C##LIBRARY"."GENRE" (
                                      "GENRE_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                      "GENRE_NAME" VARCHAR2(50 BYTE) VISIBLE DEFAULT 'Others'
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for JOB
-- ----------------------------
DROP TABLE "C##LIBRARY"."JOB";
CREATE TABLE "C##LIBRARY"."JOB" (
                                    "JOB_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                    "SALARY" NUMBER VISIBLE NOT NULL,
                                    "JOB_TITLE" VARCHAR2(100 BYTE) VISIBLE NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for MESSAGE
-- ----------------------------
DROP TABLE "C##LIBRARY"."MESSAGE";
CREATE TABLE "C##LIBRARY"."MESSAGE" (
                                        "MESSAGE_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                        "USER_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                        "MESSAGE_DATE" DATE VISIBLE NOT NULL,
                                        "MESSAGE" VARCHAR2(2000 BYTE) VISIBLE
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for NEWS
-- ----------------------------
DROP TABLE "C##LIBRARY"."NEWS";
CREATE TABLE "C##LIBRARY"."NEWS" (
                                     "NEWS_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                     "NEWS_TEXT" VARCHAR2(2000 BYTE) VISIBLE,
                                     "NEWS_DATE" DATE VISIBLE NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PUBLISHER
-- ----------------------------
DROP TABLE "C##LIBRARY"."PUBLISHER";
CREATE TABLE "C##LIBRARY"."PUBLISHER" (
                                          "PUBLISHER_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                          "NAME" VARCHAR2(100 BYTE) VISIBLE,
                                          "CITY" VARCHAR2(100 BYTE) VISIBLE,
                                          "COUNTRY" VARCHAR2(100 BYTE) VISIBLE,
                                          "POSTAL_CODE" VARCHAR2(100 BYTE) VISIBLE,
                                          "CONTACT_NO" VARCHAR2(20 BYTE) VISIBLE,
                                          "EMAIL" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
                                          "IMAGE" VARCHAR2(200 BYTE) VISIBLE DEFAULT 'https://ds.rokomari.store/rokomari110/company/publisher.png'
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for RENT_HISTORY
-- ----------------------------
DROP TABLE "C##LIBRARY"."RENT_HISTORY";
CREATE TABLE "C##LIBRARY"."RENT_HISTORY" (
                                             "RENT_HISTORY_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                             "RENT_DATE" DATE VISIBLE NOT NULL,
                                             "RETURN_DATE" DATE VISIBLE,
                                             "USER_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                             "EDITION_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for REQUEST
-- ----------------------------
DROP TABLE "C##LIBRARY"."REQUEST";
CREATE TABLE "C##LIBRARY"."REQUEST" (
                                        "USER_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                        "EDITION_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                        "COUNT" NUMBER VISIBLE NOT NULL,
                                        "REQUEST_DATE" DATE VISIBLE NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for REVIEW_RATING
-- ----------------------------
DROP TABLE "C##LIBRARY"."REVIEW_RATING";
CREATE TABLE "C##LIBRARY"."REVIEW_RATING" (
                                              "ISBN" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
                                              "USER_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                              "RATING" NUMBER(1,0) VISIBLE NOT NULL,
                                              "REVIEW" VARCHAR2(2000 BYTE) VISIBLE,
                                              "EDIT_DATE" DATE VISIBLE NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for USER
-- ----------------------------
DROP TABLE "C##LIBRARY"."USER";
CREATE TABLE "C##LIBRARY"."USER" (
                                     "USER_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                     "FIRST_NAME" VARCHAR2(20 BYTE) VISIBLE NOT NULL,
                                     "ADDRESS" VARCHAR2(100 BYTE) VISIBLE,
                                     "EMAIL" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
                                     "PASSWORD" VARCHAR2(200 BYTE) VISIBLE NOT NULL,
                                     "CONTACT_NO" VARCHAR2(20 BYTE) VISIBLE,
                                     "GENDER" CHAR(1 BYTE) VISIBLE,
                                     "IMAGE" VARCHAR2(200 BYTE) VISIBLE DEFAULT 'https://img.freepik.com/free-icon/user_318-159711.jpg',
                                     "LAST_NAME" VARCHAR2(20 BYTE) VISIBLE
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for WRITTEN_BY
-- ----------------------------
DROP TABLE "C##LIBRARY"."WRITTEN_BY";
CREATE TABLE "C##LIBRARY"."WRITTEN_BY" (
                                           "ISBN" VARCHAR2(100 BYTE) VISIBLE NOT NULL,
                                           "AUTHOR_ID" VARCHAR2(20 BYTE) VISIBLE NOT NULL
)
    LOGGING
    NOCOMPRESS
    PCTFREE 10
    INITRANS 1
    STORAGE (
    INITIAL 65536
    NEXT 1048576
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    BUFFER_POOL DEFAULT
            )
    PARALLEL 1
    NOCACHE
    DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Primary Key structure for table ADMIN
-- ----------------------------
ALTER TABLE "C##LIBRARY"."ADMIN" ADD CONSTRAINT "SYS_C008268" PRIMARY KEY ("USER_ID");

-- ----------------------------
-- Checks structure for table ADMIN
-- ----------------------------
ALTER TABLE "C##LIBRARY"."ADMIN" ADD CONSTRAINT "SYS_C008055" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table APPLY
-- ----------------------------
ALTER TABLE "C##LIBRARY"."APPLY" ADD CONSTRAINT "SYS_C008298" PRIMARY KEY ("USER_ID", "JOB_ID");

-- ----------------------------
-- Checks structure for table APPLY
-- ----------------------------
ALTER TABLE "C##LIBRARY"."APPLY" ADD CONSTRAINT "SYS_C008057" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."APPLY" ADD CONSTRAINT "SYS_C008058" CHECK ("JOB_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."APPLY" ADD CONSTRAINT "SYS_C008059" CHECK ("APPLY_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."APPLY" ADD CONSTRAINT "SYS_C008296" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."APPLY" ADD CONSTRAINT "SYS_C008297" CHECK ("JOB_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."APPLY" ADD CONSTRAINT "SYS_C008321" CHECK ("APPLY_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table AUTHOR
-- ----------------------------
ALTER TABLE "C##LIBRARY"."AUTHOR" ADD CONSTRAINT "SYS_C008232" PRIMARY KEY ("AUTHOR_ID");

-- ----------------------------
-- Checks structure for table AUTHOR
-- ----------------------------
ALTER TABLE "C##LIBRARY"."AUTHOR" ADD CONSTRAINT "SYS_C008060" CHECK ("AUTHOR_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."AUTHOR" ADD CONSTRAINT "SYS_C008061" CHECK ("DOB" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."AUTHOR" ADD CONSTRAINT "SYS_C008062" CHECK ("NATIONALITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."AUTHOR" ADD CONSTRAINT "SYS_C008063" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."AUTHOR" ADD CONSTRAINT "SYS_C008230" CHECK ("DOB" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."AUTHOR" ADD CONSTRAINT "SYS_C008231" CHECK ("NATIONALITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."AUTHOR" ADD CONSTRAINT "SYS_C008335" CHECK ("NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table BOOK
-- ----------------------------
ALTER TABLE "C##LIBRARY"."BOOK" ADD CONSTRAINT "SYS_C008236" PRIMARY KEY ("ISBN");

-- ----------------------------
-- Checks structure for table BOOK
-- ----------------------------
ALTER TABLE "C##LIBRARY"."BOOK" ADD CONSTRAINT "SYS_C008064" CHECK ("ISBN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."BOOK" ADD CONSTRAINT "SYS_C008065" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."BOOK" ADD CONSTRAINT "SYS_C008066" CHECK ("NUMBER_OF_PAGES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."BOOK" ADD CONSTRAINT "SYS_C008233" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."BOOK" ADD CONSTRAINT "SYS_C008234" CHECK ("NUMBER_OF_PAGES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table BOOK_GENRE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."BOOK_GENRE" ADD CONSTRAINT "SYS_C008264" PRIMARY KEY ("ISBN", "GENRE_ID");

-- ----------------------------
-- Checks structure for table BOOK_GENRE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."BOOK_GENRE" ADD CONSTRAINT "SYS_C008067" CHECK ("ISBN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."BOOK_GENRE" ADD CONSTRAINT "SYS_C008068" CHECK ("GENRE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."BOOK_GENRE" ADD CONSTRAINT "SYS_C008263" CHECK ("ISBN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EDITION
-- ----------------------------
ALTER TABLE "C##LIBRARY"."EDITION" ADD CONSTRAINT "SYS_C008242" PRIMARY KEY ("EDITION_ID");

-- ----------------------------
-- Uniques structure for table EDITION
-- ----------------------------
ALTER TABLE "C##LIBRARY"."EDITION" ADD CONSTRAINT "SYS_C008243" UNIQUE ("ISBN", "EDITION_NUM") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table EDITION
-- ----------------------------
ALTER TABLE "C##LIBRARY"."EDITION" ADD CONSTRAINT "SYS_C008069" CHECK ("EDITION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."EDITION" ADD CONSTRAINT "SYS_C008070" CHECK ("ISBN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."EDITION" ADD CONSTRAINT "SYS_C008071" CHECK ("EDITION_NUM" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."EDITION" ADD CONSTRAINT "SYS_C008072" CHECK ("NUM_OF_COPIES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."EDITION" ADD CONSTRAINT "SYS_C008238" CHECK ("ISBN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."EDITION" ADD CONSTRAINT "SYS_C008239" CHECK ("EDITION_NUM" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."EDITION" ADD CONSTRAINT "SYS_C008240" CHECK ("NUM_OF_COPIES" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EMPLOYEE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."EMPLOYEE" ADD CONSTRAINT "SYS_C008293" PRIMARY KEY ("USER_ID", "JOB_ID");

-- ----------------------------
-- Checks structure for table EMPLOYEE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."EMPLOYEE" ADD CONSTRAINT "SYS_C008073" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."EMPLOYEE" ADD CONSTRAINT "SYS_C008074" CHECK ("JOB_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."EMPLOYEE" ADD CONSTRAINT "SYS_C008075" CHECK ("JOIN_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."EMPLOYEE" ADD CONSTRAINT "SYS_C008290" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."EMPLOYEE" ADD CONSTRAINT "SYS_C008291" CHECK ("JOB_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."EMPLOYEE" ADD CONSTRAINT "SYS_C008292" CHECK ("JOIN_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table FAVOURITE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."FAVOURITE" ADD CONSTRAINT "SYS_C008272" PRIMARY KEY ("USER_ID", "ISBN");

-- ----------------------------
-- Checks structure for table FAVOURITE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."FAVOURITE" ADD CONSTRAINT "SYS_C008076" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."FAVOURITE" ADD CONSTRAINT "SYS_C008077" CHECK ("ISBN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."FAVOURITE" ADD CONSTRAINT "SYS_C008270" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."FAVOURITE" ADD CONSTRAINT "SYS_C008271" CHECK ("ISBN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table FINE_HISTORY
-- ----------------------------
ALTER TABLE "C##LIBRARY"."FINE_HISTORY" ADD CONSTRAINT "SYS_C008310" PRIMARY KEY ("RENT_HISTORY_ID");

-- ----------------------------
-- Checks structure for table FINE_HISTORY
-- ----------------------------
ALTER TABLE "C##LIBRARY"."FINE_HISTORY" ADD CONSTRAINT "SYS_C008078" CHECK ("RENT_HISTORY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."FINE_HISTORY" ADD CONSTRAINT "SYS_C008079" CHECK ("FEE_AMOUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."FINE_HISTORY" ADD CONSTRAINT "SYS_C008080" CHECK ("START_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."FINE_HISTORY" ADD CONSTRAINT "SYS_C008307" CHECK ("RENT_HISTORY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."FINE_HISTORY" ADD CONSTRAINT "SYS_C008308" CHECK ("FEE_AMOUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."FINE_HISTORY" ADD CONSTRAINT "SYS_C008309" CHECK ("START_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table GENRE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."GENRE" ADD CONSTRAINT "SYS_C008262" PRIMARY KEY ("GENRE_ID");

-- ----------------------------
-- Checks structure for table GENRE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."GENRE" ADD CONSTRAINT "SYS_C008081" CHECK ("GENRE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JOB
-- ----------------------------
ALTER TABLE "C##LIBRARY"."JOB" ADD CONSTRAINT "SYS_C008289" PRIMARY KEY ("JOB_ID");

-- ----------------------------
-- Checks structure for table JOB
-- ----------------------------
ALTER TABLE "C##LIBRARY"."JOB" ADD CONSTRAINT "SYS_C008082" CHECK ("JOB_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."JOB" ADD CONSTRAINT "SYS_C008083" CHECK ("SALARY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."JOB" ADD CONSTRAINT "SYS_C008084" CHECK ("JOB_TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."JOB" ADD CONSTRAINT "SYS_C008286" CHECK ("JOB_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."JOB" ADD CONSTRAINT "SYS_C008287" CHECK ("SALARY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."JOB" ADD CONSTRAINT "SYS_C008288" CHECK ("JOB_TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table MESSAGE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."MESSAGE" ADD CONSTRAINT "SYS_C008318" PRIMARY KEY ("MESSAGE_ID");

-- ----------------------------
-- Checks structure for table MESSAGE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."MESSAGE" ADD CONSTRAINT "SYS_C008085" CHECK ("MESSAGE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."MESSAGE" ADD CONSTRAINT "SYS_C008086" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."MESSAGE" ADD CONSTRAINT "SYS_C008087" CHECK ("MESSAGE_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."MESSAGE" ADD CONSTRAINT "SYS_C008315" CHECK ("MESSAGE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."MESSAGE" ADD CONSTRAINT "SYS_C008316" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."MESSAGE" ADD CONSTRAINT "SYS_C008317" CHECK ("MESSAGE_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table NEWS
-- ----------------------------
ALTER TABLE "C##LIBRARY"."NEWS" ADD CONSTRAINT "SYS_C008314" PRIMARY KEY ("NEWS_ID");

-- ----------------------------
-- Checks structure for table NEWS
-- ----------------------------
ALTER TABLE "C##LIBRARY"."NEWS" ADD CONSTRAINT "SYS_C008088" CHECK ("NEWS_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."NEWS" ADD CONSTRAINT "SYS_C008089" CHECK ("NEWS_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."NEWS" ADD CONSTRAINT "SYS_C008312" CHECK ("NEWS_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."NEWS" ADD CONSTRAINT "SYS_C008313" CHECK ("NEWS_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table PUBLISHER
-- ----------------------------
ALTER TABLE "C##LIBRARY"."PUBLISHER" ADD CONSTRAINT "SYS_C008227" PRIMARY KEY ("PUBLISHER_ID");

-- ----------------------------
-- Checks structure for table PUBLISHER
-- ----------------------------
ALTER TABLE "C##LIBRARY"."PUBLISHER" ADD CONSTRAINT "SYS_C008090" CHECK ("PUBLISHER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."PUBLISHER" ADD CONSTRAINT "SYS_C008091" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."PUBLISHER" ADD CONSTRAINT "SYS_C008226" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table RENT_HISTORY
-- ----------------------------
ALTER TABLE "C##LIBRARY"."RENT_HISTORY" ADD CONSTRAINT "SYS_C008305" PRIMARY KEY ("RENT_HISTORY_ID");

-- ----------------------------
-- Checks structure for table RENT_HISTORY
-- ----------------------------
ALTER TABLE "C##LIBRARY"."RENT_HISTORY" ADD CONSTRAINT "SYS_C008092" CHECK ("RENT_HISTORY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."RENT_HISTORY" ADD CONSTRAINT "SYS_C008093" CHECK ("RENT_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."RENT_HISTORY" ADD CONSTRAINT "SYS_C008094" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."RENT_HISTORY" ADD CONSTRAINT "SYS_C008095" CHECK ("EDITION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."RENT_HISTORY" ADD CONSTRAINT "SYS_C008301" CHECK ("RENT_HISTORY_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."RENT_HISTORY" ADD CONSTRAINT "SYS_C008302" CHECK ("RENT_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."RENT_HISTORY" ADD CONSTRAINT "SYS_C008303" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."RENT_HISTORY" ADD CONSTRAINT "SYS_C008304" CHECK ("EDITION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table REQUEST
-- ----------------------------
ALTER TABLE "C##LIBRARY"."REQUEST" ADD CONSTRAINT "SYS_C008253" PRIMARY KEY ("USER_ID", "EDITION_ID");

-- ----------------------------
-- Checks structure for table REQUEST
-- ----------------------------
ALTER TABLE "C##LIBRARY"."REQUEST" ADD CONSTRAINT "SYS_C008096" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REQUEST" ADD CONSTRAINT "SYS_C008097" CHECK ("EDITION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REQUEST" ADD CONSTRAINT "SYS_C008098" CHECK ("COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REQUEST" ADD CONSTRAINT "SYS_C008099" CHECK ("REQUEST_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REQUEST" ADD CONSTRAINT "SYS_C008250" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REQUEST" ADD CONSTRAINT "SYS_C008251" CHECK ("EDITION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REQUEST" ADD CONSTRAINT "SYS_C008252" CHECK ("COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REQUEST" ADD CONSTRAINT "SYS_C008320" CHECK ("REQUEST_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table REVIEW_RATING
-- ----------------------------
ALTER TABLE "C##LIBRARY"."REVIEW_RATING" ADD CONSTRAINT "SYS_C008332" PRIMARY KEY ("ISBN", "USER_ID");

-- ----------------------------
-- Checks structure for table REVIEW_RATING
-- ----------------------------
ALTER TABLE "C##LIBRARY"."REVIEW_RATING" ADD CONSTRAINT "SYS_C008100" CHECK ("ISBN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REVIEW_RATING" ADD CONSTRAINT "SYS_C008101" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REVIEW_RATING" ADD CONSTRAINT "SYS_C008102" CHECK ("RATING" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REVIEW_RATING" ADD CONSTRAINT "SYS_C008103" CHECK ("EDIT_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REVIEW_RATING" ADD CONSTRAINT "SYS_C008328" CHECK ("ISBN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REVIEW_RATING" ADD CONSTRAINT "SYS_C008329" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REVIEW_RATING" ADD CONSTRAINT "SYS_C008330" CHECK ("RATING" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REVIEW_RATING" ADD CONSTRAINT "SYS_C008331" CHECK ("EDIT_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table USER
-- ----------------------------
ALTER TABLE "C##LIBRARY"."USER" ADD CONSTRAINT "SYS_C008249" PRIMARY KEY ("USER_ID");

-- ----------------------------
-- Checks structure for table USER
-- ----------------------------
ALTER TABLE "C##LIBRARY"."USER" ADD CONSTRAINT "SYS_C008104" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."USER" ADD CONSTRAINT "SYS_C008105" CHECK ("FIRST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."USER" ADD CONSTRAINT "SYS_C008106" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."USER" ADD CONSTRAINT "SYS_C008107" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."USER" ADD CONSTRAINT "SYS_C008245" CHECK ("FIRST_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."USER" ADD CONSTRAINT "SYS_C008247" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."USER" ADD CONSTRAINT "SYS_C008248" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table WRITTEN_BY
-- ----------------------------
ALTER TABLE "C##LIBRARY"."WRITTEN_BY" ADD CONSTRAINT "SYS_C008258" PRIMARY KEY ("ISBN", "AUTHOR_ID");

-- ----------------------------
-- Checks structure for table WRITTEN_BY
-- ----------------------------
ALTER TABLE "C##LIBRARY"."WRITTEN_BY" ADD CONSTRAINT "SYS_C008108" CHECK ("ISBN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."WRITTEN_BY" ADD CONSTRAINT "SYS_C008109" CHECK ("AUTHOR_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."WRITTEN_BY" ADD CONSTRAINT "SYS_C008256" CHECK ("ISBN" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."WRITTEN_BY" ADD CONSTRAINT "SYS_C008257" CHECK ("AUTHOR_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table ADMIN
-- ----------------------------
ALTER TABLE "C##LIBRARY"."ADMIN" ADD CONSTRAINT "SYS_C008269" FOREIGN KEY ("USER_ID") REFERENCES "C##LIBRARY"."USER" ("USER_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table APPLY
-- ----------------------------
ALTER TABLE "C##LIBRARY"."APPLY" ADD CONSTRAINT "SYS_C008299" FOREIGN KEY ("USER_ID") REFERENCES "C##LIBRARY"."USER" ("USER_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."APPLY" ADD CONSTRAINT "SYS_C008300" FOREIGN KEY ("JOB_ID") REFERENCES "C##LIBRARY"."JOB" ("JOB_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table BOOK
-- ----------------------------
ALTER TABLE "C##LIBRARY"."BOOK" ADD CONSTRAINT "SYS_C008237" FOREIGN KEY ("PUBLISHER_ID") REFERENCES "C##LIBRARY"."PUBLISHER" ("PUBLISHER_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table BOOK_GENRE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."BOOK_GENRE" ADD CONSTRAINT "SYS_C008265" FOREIGN KEY ("ISBN") REFERENCES "C##LIBRARY"."BOOK" ("ISBN") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."BOOK_GENRE" ADD CONSTRAINT "SYS_C008266" FOREIGN KEY ("GENRE_ID") REFERENCES "C##LIBRARY"."GENRE" ("GENRE_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table EDITION
-- ----------------------------
ALTER TABLE "C##LIBRARY"."EDITION" ADD CONSTRAINT "SYS_C008244" FOREIGN KEY ("ISBN") REFERENCES "C##LIBRARY"."BOOK" ("ISBN") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table EMPLOYEE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."EMPLOYEE" ADD CONSTRAINT "SYS_C008294" FOREIGN KEY ("USER_ID") REFERENCES "C##LIBRARY"."USER" ("USER_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."EMPLOYEE" ADD CONSTRAINT "SYS_C008295" FOREIGN KEY ("JOB_ID") REFERENCES "C##LIBRARY"."JOB" ("JOB_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table FAVOURITE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."FAVOURITE" ADD CONSTRAINT "SYS_C008273" FOREIGN KEY ("USER_ID") REFERENCES "C##LIBRARY"."USER" ("USER_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."FAVOURITE" ADD CONSTRAINT "SYS_C008274" FOREIGN KEY ("ISBN") REFERENCES "C##LIBRARY"."BOOK" ("ISBN") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table FINE_HISTORY
-- ----------------------------
ALTER TABLE "C##LIBRARY"."FINE_HISTORY" ADD CONSTRAINT "SYS_C008311" FOREIGN KEY ("RENT_HISTORY_ID") REFERENCES "C##LIBRARY"."RENT_HISTORY" ("RENT_HISTORY_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table MESSAGE
-- ----------------------------
ALTER TABLE "C##LIBRARY"."MESSAGE" ADD CONSTRAINT "SYS_C008319" FOREIGN KEY ("USER_ID") REFERENCES "C##LIBRARY"."USER" ("USER_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table RENT_HISTORY
-- ----------------------------
ALTER TABLE "C##LIBRARY"."RENT_HISTORY" ADD CONSTRAINT "SYS_C008306" FOREIGN KEY ("EDITION_ID") REFERENCES "C##LIBRARY"."EDITION" ("EDITION_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table REQUEST
-- ----------------------------
ALTER TABLE "C##LIBRARY"."REQUEST" ADD CONSTRAINT "SYS_C008254" FOREIGN KEY ("USER_ID") REFERENCES "C##LIBRARY"."USER" ("USER_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REQUEST" ADD CONSTRAINT "SYS_C008255" FOREIGN KEY ("EDITION_ID") REFERENCES "C##LIBRARY"."EDITION" ("EDITION_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table REVIEW_RATING
-- ----------------------------
ALTER TABLE "C##LIBRARY"."REVIEW_RATING" ADD CONSTRAINT "SYS_C008333" FOREIGN KEY ("ISBN") REFERENCES "C##LIBRARY"."BOOK" ("ISBN") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."REVIEW_RATING" ADD CONSTRAINT "SYS_C008334" FOREIGN KEY ("USER_ID") REFERENCES "C##LIBRARY"."USER" ("USER_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table WRITTEN_BY
-- ----------------------------
ALTER TABLE "C##LIBRARY"."WRITTEN_BY" ADD CONSTRAINT "SYS_C008259" FOREIGN KEY ("ISBN") REFERENCES "C##LIBRARY"."BOOK" ("ISBN") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##LIBRARY"."WRITTEN_BY" ADD CONSTRAINT "SYS_C008260" FOREIGN KEY ("AUTHOR_ID") REFERENCES "C##LIBRARY"."AUTHOR" ("AUTHOR_ID") ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
